name: hsma_des_model_library
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - pip
  - pip:
    - matplotlib>=3.9.1,<4
    - numpy>=1.26.2,<2
    - pandas>=2.0.1,<3
    - plotly>=5.12.0,<6
    - simpy==4.0.2,<5
    - vidigi==0.0.4,<1
    - streamlit>=1.36.0,<2
